# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/IoT_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/IoT_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/IoT_Project/CMakeFiles /home/pi/Desktop/IoT_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/IoT_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IoTClient

# Build rule for target.
IoTClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IoTClient
.PHONY : IoTClient

# fast build rule for target.
IoTClient/fast:
	$(MAKE) -f CMakeFiles/IoTClient.dir/build.make CMakeFiles/IoTClient.dir/build
.PHONY : IoTClient/fast

#=============================================================================
# Target rules for targets named IoTServer

# Build rule for target.
IoTServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IoTServer
.PHONY : IoTServer

# fast build rule for target.
IoTServer/fast:
	$(MAKE) -f CMakeFiles/IoTServer.dir/build.make CMakeFiles/IoTServer.dir/build
.PHONY : IoTServer/fast

IoTClient.o: IoTClient.cpp.o

.PHONY : IoTClient.o

# target to build an object file
IoTClient.cpp.o:
	$(MAKE) -f CMakeFiles/IoTClient.dir/build.make CMakeFiles/IoTClient.dir/IoTClient.cpp.o
.PHONY : IoTClient.cpp.o

IoTClient.i: IoTClient.cpp.i

.PHONY : IoTClient.i

# target to preprocess a source file
IoTClient.cpp.i:
	$(MAKE) -f CMakeFiles/IoTClient.dir/build.make CMakeFiles/IoTClient.dir/IoTClient.cpp.i
.PHONY : IoTClient.cpp.i

IoTClient.s: IoTClient.cpp.s

.PHONY : IoTClient.s

# target to generate assembly for a file
IoTClient.cpp.s:
	$(MAKE) -f CMakeFiles/IoTClient.dir/build.make CMakeFiles/IoTClient.dir/IoTClient.cpp.s
.PHONY : IoTClient.cpp.s

IoTServer.o: IoTServer.cpp.o

.PHONY : IoTServer.o

# target to build an object file
IoTServer.cpp.o:
	$(MAKE) -f CMakeFiles/IoTServer.dir/build.make CMakeFiles/IoTServer.dir/IoTServer.cpp.o
.PHONY : IoTServer.cpp.o

IoTServer.i: IoTServer.cpp.i

.PHONY : IoTServer.i

# target to preprocess a source file
IoTServer.cpp.i:
	$(MAKE) -f CMakeFiles/IoTServer.dir/build.make CMakeFiles/IoTServer.dir/IoTServer.cpp.i
.PHONY : IoTServer.cpp.i

IoTServer.s: IoTServer.cpp.s

.PHONY : IoTServer.s

# target to generate assembly for a file
IoTServer.cpp.s:
	$(MAKE) -f CMakeFiles/IoTServer.dir/build.make CMakeFiles/IoTServer.dir/IoTServer.cpp.s
.PHONY : IoTServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... IoTClient"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... IoTServer"
	@echo "... IoTClient.o"
	@echo "... IoTClient.i"
	@echo "... IoTClient.s"
	@echo "... IoTServer.o"
	@echo "... IoTServer.i"
	@echo "... IoTServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

